// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0GzGiygaM-SE3pvYTyXbhOMNOLP2wYHg',
    appId: '1:311446614144:android:2959a2c8cc2b10d2b9f665',
    messagingSenderId: '311446614144',
    projectId: 'bmi-calc-9b3df',
    databaseURL: 'https://bmi-calc-9b3df-default-rtdb.firebaseio.com',
    storageBucket: 'bmi-calc-9b3df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUa_oTQTuBEduRbWDWUbNN0jd5D_gtio',
    appId: '1:311446614144:ios:eb33cea9e039f0f9b9f665',
    messagingSenderId: '311446614144',
    projectId: 'bmi-calc-9b3df',
    databaseURL: 'https://bmi-calc-9b3df-default-rtdb.firebaseio.com',
    storageBucket: 'bmi-calc-9b3df.appspot.com',
    iosBundleId: 'com.example.anApp',
  );
}
